import {Food} from './app/shared/models/food'

export const sample_foods: Food[] = [
    {
        id:  "1",
        name: "Pho",
        price: 10,
        tags: ['Soup', 'Asian','Vietnamese'],
        favorite: false,
        stars: 5.0,
        imageURL: 'assets/pho.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "5+ hours",
    },
    {
        id:  "2",
        name: "Banh Canh",
        price: 8,
        tags: ['Soup', 'Asian','Vietnamese'],
        favorite: false,
        stars: 4.0,
        imageURL: 'assets/banh-canh.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "2+ hours",
    },
    {
        id:  "3",
        name: "Banh Xeo",
        price: 6,
        tags: ['Pancake', 'Asian','Vietnamese'],
        favorite: false,
        stars: 4.5,
        imageURL: 'assets/banh-xeo.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "1 hour",
    },
    {
        id:  "4",
        name: "Banh Bot Lop",
        price: 5,
        tags: ['Tapioca', 'Asian','Vietnamese'],
        favorite: true,
        stars: 4.8,
        imageURL: 'assets/banh-bot-lop.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "1 hour",
    },
    {
        id:  "5",
        name: "Cha Gio",
        price: 3,
        tags: ['Eggroll', 'Asian','Vietnamese'],
        favorite: true,
        stars: 4.0,
        imageURL: 'assets/cha-gio.png',
        origins: ['Vietnam', 'Asia'],
        cookTime: "1 hour",
    },
    {
        id:  "6",
        name: "Com Dac Biet",
        price: 12,
        tags: ['Rice', 'Meat', 'Asian','Vietnamese'],
        favorite: false,
        stars: 4.8,
        imageURL: 'assets/com-dac-biet.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "1+ hours",
    },
    {
        id:  "7",
        name: "Banh Mi",
        price: 5,
        tags: ['Sandwhich', 'Bread', 'Asian','Vietnamese'],
        favorite: true,
        stars: 4.0,
        imageURL: 'assets/banh-mi.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "30-45",
    },
    {
        id:  "8",
        name: "Banh Beo",
        price: 8,
        tags: ['Ricecake', 'Steamed', 'Asian','Vietnamese'],
        favorite: false,
        stars: 4.2,
        imageURL: 'assets/banh-beo.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "1 hour",
    },
    {
        id:  "9",
        name: "Banh Khot",
        price: 8,
        tags: ['Pancake', 'Asian','Vietnamese'],
        favorite: false,
        stars: 4.7,
        imageURL: 'assets/banh-khot.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "1 hour",
    },
    {
        id:  "10",
        name: "Banh Bo",
        price: 10,
        tags: ['Honeycomb', 'Pandan', 'Cake', 'Asian','Vietnamese'],
        favorite: true,
        stars: 4.8,
        imageURL: 'assets/banh-bo.jpeg',
        origins: ['Vietnam', 'Asia'],
        cookTime: "1+ hours",
    },


    
    
    

]